name: Continuous Integration with Github Actions

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Set up JDK 19
      uses: actions/setup-java@v3
      with:
        java-version: '19'
        distribution: 'adopt'
        cache: maven
        
    - name: Build application JAR
      working-directory: '' # ./java/rest-w-spring-java-triluna
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ../
      run: docker compose build
      
    - name: Push to Docker Hub Container Registry
      run: | 
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-spring-erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest-spring-erudio:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-erudio:${{ github.run_id }}
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-spring-erudio:latest
